// web/src/components/AuthFooter.tsx
import Link from "next/link";

export default function AuthFooter({
  text,
  linkText,
  linkTo,
}: {
  text: string;
  linkText: string;
  linkTo: string;
}) {
  return (
    <footer className="absolute bottom-6 text-gray font-medium text-sm text-center left-0 right-0">
      <div className="gradient-highlight w-full h-[1px]"></div>
      <p className="mt-6">
        {text}
        <Link href={linkTo} className="text-white">
          {" "}
          {linkText}
        </Link>
        .
      </p>
    </footer>
  );
}

// web/src/lib/components/auth/AuthFooter.svelte
<script lang="ts">
	type Props = {
		text: string;
		linkText: string;
		linkTo: string;
	};

	let { text, linkText, linkTo }: Props = $props();
</script>

<footer class="absolute right-0 bottom-6 left-0 text-center text-sm font-medium text-gray">
	<div class="gradient-border h-[1px] w-full"></div>
	<p class="mt-6">
		{text}
		<a href={linkTo} class="text-foreground"> {linkText} </a>
		.
	</p>
</footer>
