// web/src/routes/(auth)/signup/+page.svelte
<script lang="ts">
	import { CircleArrowLeft, X } from '@lucide/svelte';

	import { resolve } from '$app/paths';

	import AuthContent from '$components/auth/AuthContent.svelte';
	import AuthFooter from '$components/auth/AuthFooter.svelte';
	import RotatingQuotes from '$components/auth/RotatingQuotes.svelte';
	import SignupForm from '$components/auth/SignupForm.svelte';

	let pageState = $state({ page: 1 });
	let reduceMotion = $state(false);

	$effect(() => {
		const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
		reduceMotion = mq.matches;
		const handler = (e: MediaQueryListEvent) => (reduceMotion = e.matches);
		mq.addEventListener?.('change', handler);

		return () => mq.removeEventListener?.('change', handler);
	});

	function handleClick() {
		pageState.page = 1;
	}
</script>

{#if !reduceMotion}
	<div
		aria-hidden={true}
		class="signup-animated-mesh absolute top-24 right-0 bottom-0 left-0 m-auto h-1/2 w-1/2"
	></div>
{/if}

<div
	aria-hidden={true}
	class="pointer-events-none fixed inset-0 z-0 bg-black/70 backdrop-blur-3xl"
></div>

<main class="relative flex w-full flex-1 flex-col items-center justify-center">
	<a
		href={resolve('/')}
		aria-label="Close and go to home"
		class="absolute top-2 left-2 rounded-full bg-white/[0.03] p-1 text-foreground transition-colors duration-200 hover:bg-white/5 md:top-8"
	>
		<X size={18} />
	</a>

	<div class={`mb-3 h-12 ${pageState.page === 2 ? 'block' : 'hidden'}`}>
		<RotatingQuotes />
	</div>

	<div class="relative animate-fade-in">
		{#if pageState.page === 1}
			<AuthContent
				title="Welcome to FrameRate"
				description="Thank you for being an early adopter. Let's set up your account."
			/>
		{/if}

		<section>
			{#if pageState.page === 2}
				<button
					type="button"
					onclick={handleClick}
					class="mb-7 w-fit text-gray transition-colors duration-200 hover:text-foreground"
				>
					<CircleArrowLeft size={32} strokeWidth={1.1} />
				</button>
			{/if}
			<SignupForm {pageState} />
		</section>
	</div>
</main>

<AuthFooter text="Already have an account?" linkText="Login" linkTo="/login" />

// web/apps/web/src/routes/(auth)/signup.tsx
import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";

import AuthContent from "@web/features/auth/components/AuthContent";
import AuthFooter from "@web/features/auth/components/AuthFooter";
import RotatingQuotes from "@web/features/auth/components/RotatingQuotes";
import SignupForm from "@web/features/auth/components/SignupForm";

import { CircleArrowLeft, X } from "lucide-react";

export const Route = createFileRoute("/(auth)/signup")({
  component: SignupPage,
});

function SignupPage() {
  const [page, setPage] = useState(1);

  function handleClick() {
    setPage(1);
  }

  return (
    <>
      <div
        aria-hidden={true}
        className="signup-animated-mesh absolute top-0 right-0 bottom-0 left-0 m-auto h-[400px] w-[500px]"
      />
      <div
        aria-hidden={true}
        className="absolute top-0 left-0 z-0 size-full bg-black/75 backdrop-blur-3xl"
      />
      <main className="relative flex h-full flex-col items-center justify-center">
        <Link
          to="/"
          className="text-foreground absolute top-8 left-2 rounded-full bg-white/[0.03] p-1 transition-colors duration-200 hover:bg-white/5"
        >
          <X size={18} />
        </Link>

        <div className={`mb-24 h-12 ${page === 2 ? "block" : "hidden"}`}>
          <RotatingQuotes />
        </div>

        <div className="animate-fade-in">
          <div className="relative bottom-[70px]">
            {page === 1 && (
              <AuthContent
                title="Welcome to FrameRate"
                description="Thank you for being an early adopter. Let's set up your account."
              />
            )}

            <section>
              {page === 2 && (
                <button
                  type="button"
                  onClick={handleClick}
                  className="text-gray hover:text-foreground mb-4 w-fit transition-colors duration-200"
                >
                  <CircleArrowLeft size={32} strokeWidth={1.1} />
                </button>
              )}
              <SignupForm page={page} setPage={setPage} />
            </section>
          </div>
        </div>
      </main>

      <AuthFooter
        text="Already have an account?"
        linkText="Login"
        linkTo="/login"
      />
    </>
  );
}
