// web/src/lib/components/details/backdrop.svelte
<script lang="ts">
	type Props = {
		collection?: boolean;
		alt: string;
		backdropPath: string;
	};

	let { collection = false, alt, backdropPath }: Props = $props();

	let imageLoaded = $state(false);
	let imageRef: HTMLImageElement | undefined = $state();

	function handleImageLoad() {
		imageLoaded = true;
	}

	// Cached images will be complete
	$effect(() => {
		if (imageRef && imageRef.complete) {
			imageLoaded = true;
		}

		// Fallback timer for any edge cases
		const timer = setTimeout(() => {
			imageLoaded = true;
		}, 1000);

		return () => clearTimeout(timer);
	});
</script>

{#if backdropPath}
	<div class="relative m-auto h-auto w-full overflow-hidden">
		<img
			bind:this={imageRef}
			src={`https://image.tmdb.org/t/p/original${backdropPath}`}
			sizes="100vw"
			{alt}
			loading="lazy"
			decoding="async"
			fetchpriority="auto"
			width={1920}
			height={1080}
			onload={handleImageLoad}
			class={`${imageLoaded ? 'animate-fade-in' : 'opacity-0'} ${collection ? 'h-[450px]' : 'h-auto'} w-full object-cover`}
		/>
		<!-- Tablet and Desktop shadow gradient -->
		<div
			class={`${collection ? 'h-[550px]' : 'md:h-[455px] lg:h-[675px] xl:h-[700px]'} backdrop-fade pointer-events-none absolute top-0 hidden w-full bg-no-repeat md:block`}
		></div>
		<!-- Mobile shadow gradient -->
		<div
			class="pointer-events-none absolute top-0 block size-full bg-gradient-to-t from-neutral-900 via-transparent to-transparent bg-no-repeat md:hidden"
		></div>
	</div>
{/if}

// web/src/features/details/components/backdrop.tsx
import { useEffect, useRef, useState } from 'react';

type BackdropProps = {
  collection?: boolean;
  alt: string;
  backdropPath: string;
};

export default function Backdrop({
  alt,
  backdropPath,
  collection = false,
}: BackdropProps) {
  const [imageLoaded, setImageLoaded] = useState(false);
  const imageRef = useRef<HTMLImageElement>(null);

  function handleImageLoad() {
    setImageLoaded(true);
  }

  // Cached images will be complete
  useEffect(() => {
    if (imageRef.current && imageRef.current.complete) {
      setImageLoaded(true);
    }

    // Fallback timer for any edge cases
    const timer = setTimeout(() => {
      setImageLoaded(true);
    }, 1000);

    return () => clearTimeout(timer);
  }, []);

  return (
    backdropPath && (
      <div className={`relative -z-10 m-auto h-auto w-full overflow-hidden`}>
        <img
          ref={imageRef}
          src={`https://image.tmdb.org/t/p/original${backdropPath}`}
          alt={alt}
          width={1920}
          height={1080}
          onLoad={handleImageLoad}
          className={`${imageLoaded ? 'animate-fade-in' : 'opacity-0'} ${collection ? 'h-[450px]' : 'h-auto'} w-full object-cover`}
        />
        {/* Tablet and Desktop shadow gradient */}
        <div
          className={`${collection ? 'h-[550px]' : 'md:h-[455px] lg:h-[675px] xl:h-[700px]'} backdrop-fade pointer-events-none absolute top-0 hidden w-full bg-no-repeat md:block`}
        />
        {/* Mobile shadow gradient */}
        <div className="pointer-events-none absolute top-0 block size-full bg-gradient-to-t from-neutral-900 via-transparent to-transparent bg-no-repeat md:hidden" />
      </div>
    )
  );
}
