// web/src/lib/components/details/lists.svelte
<script lang="ts">
	import type { NormalizedDetails } from '$lib/types/details';

	import Check from '@lucide/svelte/icons/check';
	import Square from '@lucide/svelte/icons/square';
	import { useConvexClient, useQuery } from 'convex-svelte';
	import { toast } from 'svelte-sonner';

	import { api } from '$convex/_generated/api';

	type SavedToList = {
		listId: number;
		listItemId: number;
		mediaType: string;
		mediaId: number | null;
	};

	type Props = {
		media: NormalizedDetails;
		savedToLists: SavedToList[];
		onSavedListsChange: (lists: SavedToList[]) => void;
	};

	let { media, savedToLists, onSavedListsChange }: Props = $props();

	const convex = useConvexClient();

	// Query user's lists from Convex
	const listsQuery = useQuery(api.lists.getLists, () => ({}));

	const lists = $derived($listsQuery.data ?? []);
	const { mediaType, id: mediaId } = media;

	async function handleClick(listId: number) {
		const matchedLists = savedToLists.filter((savedList) => savedList.listId === listId);

		try {
			// Add to list
			if (matchedLists.length === 0) {
				await convex.mutation(api.lists.addListItem, {
					listId,
					mediaType,
					tmdbId: mediaId
				});
				// Optimistically update UI
				const newItem: SavedToList = {
					listId,
					listItemId: 0, // Will be set by mutation
					mediaType,
					mediaId
				};
				onSavedListsChange([...savedToLists, newItem]);
				toast.success('Added to list');
			}
			// Remove from list
			else {
				const listItem = matchedLists[0];
				// Note: This assumes listItemId is a Convex ID
				// You may need to adjust based on your actual schema
				await convex.mutation(api.lists.removeListItem, {
					listItemId: listItem.listItemId as any
				});
				const newSavedToLists = savedToLists.filter((l) => l.listId !== listId);
				onSavedListsChange(newSavedToLists);
				toast.success('Removed from list');
			}
		} catch (error) {
			const message = error instanceof Error ? error.message : 'Failed to update list';
			toast.error(message);
		}
	}

	const idList = $derived(savedToLists.map((saved) => saved.listId));
</script>

{#if lists.length > 0}
	{#each lists as list (list.id)}
		<label class="mb-2.5 flex w-fit cursor-pointer items-center select-none">
			<input
				type="checkbox"
				name="listId"
				value={list.id}
				checked={idList.includes(list.id)}
				onclick={() => handleClick(list.id)}
				class="peer hidden"
			/>
			<Check size={20} color="#00e4f5" class="hidden peer-checked:block" />
			<Square size={20} color="#262626" class="peer-checked:hidden" />
			<span class="ml-1.5">{list.name}</span>
		</label>
	{/each}
{/if}

// web/src/features/details/components/lists.tsx
import type { MediaDetails } from '@/types/details';
import type { Dispatch, SetStateAction } from 'react';

import { useEffect, useRef } from 'react';

import { useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';

import { BoxIcon } from '@/components/icons/box-icon';
import { CheckBoxIcon } from '@/components/icons/checkbox-icon';
import { addListItem, deleteListItem, getLists } from '@/server/lists';
import { useAuthStore } from '@/store/auth/auth-store';
import { useListStore } from '@/store/lists/list-store';

type SavedToList = {
  listId: number;
  listItemId: number;
  mediaType: string;
  mediaId: number | null;
};

type ListsProps = {
  media: MediaDetails;
  savedToLists: SavedToList[];
  setSavedToLists: Dispatch<SetStateAction<SavedToList[]>>;
};

export default function Lists({
  media,
  savedToLists,
  setSavedToLists,
}: ListsProps) {
  const checkboxRef = useRef<HTMLInputElement>(null);

  const { username } = useAuthStore();

  const lists = useListStore.use.lists();
  const setLists = useListStore.use.setLists();
  const clearLists = useListStore.use.clearLists();

  const { mediaType, id: mediaId } = media;

  const queryClient = useQueryClient();

  const { data: listsData, isFetching } = useQuery({
    queryKey: ['lists'],
    queryFn: async () => await getLists(),
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
  });

  useEffect(() => {
    if (!isFetching) {
      if (!listsData) {
        toast.error('Failed to get lists!');
        return;
      }

      if (listsData.error) {
        toast.error(listsData.error.message);
        return;
      }

      setLists(listsData.data);
    }
  }, [isFetching, listsData, lists.length, setLists, clearLists]);

  async function handleClick(listId: number) {
    const matchedLists = savedToLists.filter(
      (savedList) => savedList.listId === listId,
    );

    // Clicked list does not match a list that the item is saved in (if any)
    if (matchedLists.length === 0) {
      const requestData = { listId, mediaType, mediaId };

      const response = await addListItem(requestData);

      if (response.error) {
        return toast.error(response.error.message);
      }

      const { data } = response;

      setSavedToLists((prevState) => {
        const mediaId = mediaType === 'movie' ? data.movieId : data.seriesId;
        return [
          ...prevState,
          {
            listId: data.listId,
            listItemId: data.id,
            mediaType: data.mediaType,
            mediaId,
          },
        ];
      });

      toast.success('Added to list');
    }

    // Clicked list matches a list that the item is saved in
    if (matchedLists.length > 0) {
      matchedLists.forEach(async (list) => {
        const { listItemId } = list;

        const response = await deleteListItem(listItemId);

        if (response.error) {
          return toast.error(response.error.message);
        }

        const newSavedToLists = savedToLists.filter(
          (list) => list.listId !== listId,
        );

        setSavedToLists(newSavedToLists);

        toast.success('Removed from list');
      });
    }

    const listData = lists.filter((list) => list.id === listId)[0];

    if (listData) {
      queryClient.invalidateQueries({
        queryKey: ['list-items', username, listData.slug],
      });
    }
  }

  const idList = savedToLists.map((savedToLists) => savedToLists.listId);

  return (
    lists.length > 0 &&
    lists.map((list) => {
      return (
        <label
          key={list.id}
          className="mb-2.5 flex w-fit cursor-pointer items-center select-none"
        >
          <input
            ref={checkboxRef}
            type="checkbox"
            name="listId"
            value={list.id}
            defaultChecked={idList.includes(list.id)}
            onClick={() => handleClick(list.id)}
            className="peer hidden"
          />
          <CheckBoxIcon
            fillPrimary="#00e4f5"
            fillSecondary="#262626"
            classes="hidden peer-checked:block"
          />
          <BoxIcon fill="#262626" classes="peer-checked:hidden" />
          <span className="ml-1.5">{list.name}</span>
        </label>
      );
    })
  );
}
