// web/src/lib/components/details/media-actions.svelte
<script lang="ts">
	import type { NormalizedDetails } from '$lib/types/details';

	import Bookmark from '@lucide/svelte/icons/bookmark';
	import Eye from '@lucide/svelte/icons/eye';
	import Heart from '@lucide/svelte/icons/heart';
	import { useConvexClient, useQuery } from 'convex-svelte';
	import { toast } from 'svelte-sonner';

	import { api } from '$convex/_generated/api';
	import * as Tooltip from '$components/ui/tooltip';

	import CreateList from './create-list.svelte';
	import ListsModal from './lists-modal.svelte';
	import Lists from './lists.svelte';

	type SavedToList = {
		listId: number;
		listItemId: number;
		mediaType: string;
		mediaId: number | null;
	};

	type Props = {
		media: NormalizedDetails;
	};

	let { media }: Props = $props();

	let savedToLists = $state<SavedToList[]>([]);

	const { id: mediaId, mediaType } = media;

	const convex = useConvexClient();

	// Query user's review to get like/watched status
	const reviewQuery = useQuery(api.details.getUserReview, () => ({
		userId: undefined, // Will be set by auth
		mediaType,
		tmdbId: mediaId
	}));

	// Query list items for this media
	const listItemsQuery = useQuery(api.lists.getListItemsForMedia, () => ({
		mediaType,
		tmdbId: mediaId
	}));

	const isLiked = $derived(reviewQuery.data?.liked ?? false);
	const isWatched = $derived(reviewQuery.data?.watched ?? false);

	$effect(() => {
		const items = listItemsQuery.data ?? [];
		savedToLists = items;
	});

	const actions = [
		{
			id: 1,
			name: 'like' as const,
			content: 'Like',
			icon: Heart,
			active: 'fill-[#FF153A]',
			hover: 'hover:fill-[#FF153A]'
		},
		{
			id: 2,
			name: 'watch' as const,
			content: 'Mark watched',
			icon: Eye,
			active: 'fill-[#00e4f5]',
			hover: 'hover:fill-[#00e4f5]'
		}
	];

	async function handleClick(actionName: 'like' | 'watch') {
		if (!reviewQuery.data) {
			toast.info('Please submit a rating first');
			return;
		}

		try {
			if (actionName === 'like') {
				await convex.mutation(api.reviews.updateLikeStatus, {
					mediaType,
					tmdbId: mediaId,
					liked: !isLiked
				});
			} else {
				await convex.mutation(api.reviews.updateWatchedStatus, {
					mediaType,
					tmdbId: mediaId,
					watched: !isWatched
				});
			}
		} catch (error) {
			const message = error instanceof Error ? error.message : 'Failed to update';
			toast.error(message);
		}
	}

	function handleSavedListsChange(lists: SavedToList[]) {
		savedToLists = lists;
	}
</script>

<div class="mt-3 flex w-full items-center justify-evenly gap-0 px-1.5">
	<Tooltip.Provider>
		{#each actions as action (action.id)}
			{@const Icon = action.icon}
			{@const isActive =
				(action.name === 'like' && isLiked) || (action.name === 'watch' && isWatched)}
			<Tooltip.Root>
				<Tooltip.Trigger>
					{#snippet child(props)}
						<button {...props.builder} use:props.builder.action type="button">
							<Icon
								size={32}
								fill="#333"
								class={`${action.hover} ${isActive && action.active} ease h-8 cursor-pointer transition-all duration-150 active:scale-90`}
								onclick={() => handleClick(action.name)}
							/>
						</button>
					{/snippet}
				</Tooltip.Trigger>
				<Tooltip.Content side="top" sideOffset={12}>
					<p>{action.content}</p>
				</Tooltip.Content>
			</Tooltip.Root>
		{/each}

		<ListsModal
			title="Update Collections"
			description="Save or remove content from your collections"
		>
			{#snippet trigger()}
				<Tooltip.Root>
					<Tooltip.Trigger>
						{#snippet child(props)}
							<button {...props.builder} use:props.builder.action type="button">
								<Bookmark
									size={32}
									fill="#333"
									class={`${savedToLists.length > 0 && 'fill-[#32EC44]'} h-8 cursor-pointer hover:fill-[#32EC44]`}
								/>
							</button>
						{/snippet}
					</Tooltip.Trigger>
					<Tooltip.Content side="top" sideOffset={12}>
						<p>Save</p>
					</Tooltip.Content>
				</Tooltip.Root>
			{/snippet}
			{#snippet children()}
				<div class="animate-fade-in">
					<CreateList />
					<Lists {media} {savedToLists} onSavedListsChange={handleSavedListsChange} />
				</div>
			{/snippet}
		</ListsModal>
	</Tooltip.Provider>
</div>

// web/src/features/details/components/MediaActions.tsx
import type { Details } from "@/types/tmdb.types";

import { useEffect, useState } from "react";

import { toast } from "sonner";

import { useReviewStore } from "@/store/details/review-store";
import {
  BookmarkIcon,
  EyeIcon,
  HeartIcon,
  PenIcon,
} from "@/components/icons/MediaActionIcons";
import Tooltip from "@/components/Tooltip";
import { TooltipProvider } from "@/components/ui/tooltip-ui";
import CreateList from "@/features/details/components/CreateList";
import Lists from "@/features/details/components/Lists";
import ListsModal from "@/features/details/components/ListsModal";
import { checkIfListItem } from "@/features/details/server/db/list";
import {
  getReview,
  updateLikeStatus,
  updateWatchStatus,
} from "@/features/details/server/db/review";
import { authClient } from "@/lib/auth-client";

type SavedToList = {
  listId: number;
  listItemId: number;
  mediaType: string;
  mediaId: number | null;
};

export default function MediaActions({ media }: Record<"media", Details>) {
  const { isLiked, setIsLiked, isWatched, setIsWatched } = useReviewStore();
  const [savedToLists, setSavedToLists] = useState<SavedToList[]>([]);

  const { id: mediaId, mediaType } = media;

  useEffect(() => {
    (async () => {
      const reviewResult = await getReview(mediaType, mediaId);
      if (reviewResult) {
        setIsLiked(reviewResult.liked);
        setIsWatched(reviewResult.watched);
      }
    })();

    return () => {
      setIsLiked(false);
      setIsWatched(false);
    };
  }, [mediaType, mediaId, setIsLiked, setIsWatched]);

  useEffect(() => {
    (async () => {
      const savedItems = await checkIfListItem(mediaId, mediaType);
      if (savedItems && savedItems.length > 0) {
        setSavedToLists(savedItems);
      }
    })();

    return () => setSavedToLists([]);
  }, [mediaId, mediaType]);

  async function handleClick(icon: string) {
    const session = await authClient.getSession();

    if (!session?.data?.user) {
      toast.info("Please log in to save data");
      return;
    }

    switch (icon) {
      case "like":
        await updateLikeStatus({
          status: !isLiked,
          mediaId,
          mediaType,
        });
        setIsLiked(!isLiked);
        break;
      case "watch":
        await updateWatchStatus({
          status: !isWatched,
          mediaId,
          mediaType,
        });
        setIsWatched(!isWatched);
        break;
      default:
        toast.error("Something went wrong! Please try again later.");
        break;
    }
  }

  const actions = [
    {
      id: 1,
      name: "like",
      content: "Like",
      icon: HeartIcon,
      classes: `${isLiked && "fill-[#FF153A]"} cursor-pointer hover:fill-[#FF153A]`,
    },
    {
      id: 2,
      name: "watch",
      content: "Mark as watched",
      icon: EyeIcon,
      classes: `${isWatched && "fill-[#00e4f5]"} hover:fill-[#00e4f5]`,
    },
    {
      id: 4,
      name: "review",
      content: "Review",
      icon: PenIcon,
      classes: `hover:fill-[#7468F3] cursor-pointer`,
    },
  ];

  return (
    <div className="mt-3 flex w-full items-center justify-between gap-0 px-1.5">
      <TooltipProvider>
        {actions.map((action) => {
          const Icon = action.icon;

          return (
            <Tooltip
              key={action.id}
              side="top"
              sideOffset={12}
              content={action.content}
            >
              {/* Div is necessary for tooltip to work */}
              <div>
                <Icon
                  fill="#333"
                  classes={`${action.classes} cursor-pointer ease transition-all duration-150 active:scale-90 md:h-7 lg:h-8`}
                  onClick={() => handleClick(action.name)}
                />
              </div>
            </Tooltip>
          );
        })}

        <ListsModal>
          <Tooltip side="top" sideOffset={12} content={"Save to list"}>
            <ListsModal.Trigger asChild>
              {/* Div is necessary for tooltip to work */}
              <div>
                <BookmarkIcon
                  fill="#333"
                  classes={`${savedToLists && savedToLists.length > 0 && "fill-[#32EC44]"} hover:fill-[#32EC44] h-8 cursor-pointer`}
                />
              </div>
            </ListsModal.Trigger>
          </Tooltip>

          <ListsModal.Content
            title="Update Collections"
            description="Save or remove content from your collections"
          >
            <div className="animate-fade-in">
              <CreateList />
              <Lists
                media={media}
                savedToLists={savedToLists}
                setSavedToLists={setSavedToLists}
              />
            </div>
          </ListsModal.Content>
        </ListsModal>
      </TooltipProvider>
    </div>
  );
}
