// web/apps/web/src/features/home/components/HomeCarousel.tsx
import type { Trending } from "@web/types/trending";

import { useState } from "react";
import { Link } from "@tanstack/react-router";

import Poster from "@web/components/Poster";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@web/components/ui/carousel";
import { getSimpleTitle } from "@web/utils/strings";

type HomeComponentProps = {
  trendingMovies: Trending<"movie">[];
  trendingTv: Trending<"tv">[];
};

export default function HomeCarousel({
  trendingMovies,
  trendingTv,
}: HomeComponentProps) {
  const [movieData] = useState(trendingMovies);
  const [tvData] = useState(trendingTv);

  const groupedData = [
    {
      type: "movie",
      title: "Movies Making Waves",
      link: "/films/$id/$title",
      data: movieData,
    },
    {
      type: "tv",
      title: "Series Sensations",
      link: "/series/$id/$title",
      data: tvData,
    },
  ];

  return (
    <div className="animate-fade-in">
      {groupedData.map((group) => {
        const { data } = group;

        return (
          <section
            key={group.title}
            className="carousel-container group/trending"
          >
            <h2 className="mb-3 ml-2 text-lg font-medium">{group.title}</h2>
            <Carousel
              opts={{
                align: "start",
                startIndex: 0,
                skipSnaps: true,
              }}
            >
              <CarouselContent>
                {data?.map((media, index) => {
                  const simpleTitle = getSimpleTitle(media.title);
                  const loadingStrategy = index < 6 ? "eager" : "lazy";

                  return (
                    <CarouselItem
                      key={media.id}
                      className="md:basis-1/5 xl:basis-1/6"
                    >
                      <Link
                        to={group.link}
                        params={{
                          id: String(media.id),
                          title: simpleTitle,
                        }}
                      >
                        <Poster
                          title={media.title}
                          src={media.posterPath}
                          fetchSize="w342"
                          width={160}
                          height={240}
                          perspectiveEnabled={false}
                          scale={105}
                          loading={loadingStrategy}
                          classes="carousel-item w-[170px] h-[255px]"
                        />
                      </Link>
                    </CarouselItem>
                  );
                })}
              </CarouselContent>
              <CarouselPrevious className="group/trending animate-fade-in hidden md:group-hover/trending:flex" />
              <CarouselNext className="group/trending animate-fade-in hidden md:group-hover/trending:flex" />
            </Carousel>
          </section>
        );
      })}
    </div>
  );
}

// web/src/lib/components/home/home-carousel.svelte
<script lang="ts">
	// import type { Trending } from '@/types/trending';

	import { slugify } from '$utils/strings';

	import { resolve } from '$app/paths';

	import Poster from '$components/shared/poster.svelte';
	import * as Carousel from '$components/ui/carousel/index.js';

	type Props = {
		trendingMovies: Trending<'movie'>[];
		trendingTv: Trending<'tv'>[];
	};

	let { trendingMovies, trendingTv }: Props = $props();

	let movieData = $state(trendingMovies);
	let tvData = $state(trendingTv);

	const groupedData = [
		{
			type: 'movie',
			title: 'Movies Making Waves',
			link: '/films/$id/$title',
			data: movieData
		},
		{
			type: 'tv',
			title: 'Series Sensations',
			link: '/series/$id/$title',
			data: tvData
		}
	];
</script>

<div class="animate-fade-in">
	{#each groupedData as group (group.title)}
		{@const { data } = group}

		<section class="carousel-container group/trending">
			<h2 class="mb-3 ml-2 text-lg font-medium">{group.title}</h2>
			<Carousel.Root
				opts={{
					align: 'start',
					startIndex: 0,
					skipSnaps: true
				}}
			>
				<Carousel.Content>
					{#each data as media, index (index)}
						{@const titleSlug = slugify(media.title)}
						{@const loadingStrategy = index < 7 ? 'eager' : 'lazy'}
						{@const fetchStrategy = index < 7 ? 'high' : 'low'}

						<Carousel.Item>
							<a href={resolve(group.link, { id: String(media.id), title: titleSlug })}>
								<Poster
									title={media.title}
									src={media.posterPath}
									fetchSize="w342"
									width={160}
									height={240}
									perspectiveEnabled={false}
									scale={105}
									loading={loadingStrategy}
									fetchPriority={fetchStrategy}
									classes="w-fit aspect-[2/3] h-[160px] md:h-[195px] lg:h-[245px]"
								/>
							</a>
						</Carousel.Item>
					{/each}
				</Carousel.Content>
				<Carousel.Previous
					class="group/trending hidden animate-fade-in md:group-hover/trending:flex"
				/>
				<Carousel.Next class="group/trending hidden animate-fade-in md:group-hover/trending:flex" />
			</Carousel.Root>
		</section>
	{/each}
</div>
