// web/src/routes/+page.svelte
<script lang="ts">
	import { Fingerprint, Ticket } from '@lucide/svelte';
</script>

<div class="relative min-h-screen">
	<header>
		<nav class="flex items-center justify-between md:pt-8">
			<a href="/">
				<h1 class="text-lg font-extrabold md:text-3xl">FrameRate</h1>
			</a>

			<div class="flex items-center gap-4 text-sm font-semibold md:gap-10 md:text-base">
				<a href="/login" class="group/login flex items-center gap-1.5 md:gap-2">
					<span class="text-gray group-hover/login:text-foreground transition-colors duration-200">
						<Fingerprint size={18} />
					</span>
					Login
				</a>

				<a href="/signup" class="group/signup peer flex items-center gap-1.5 md:gap-2">
					<span class="text-gray group-hover/signup:text-foreground transition-colors duration-200">
						<Ticket size={18} />
					</span>
					Create free account
				</a>
			</div>
		</nav>
	</header>

	<main class="mx-auto">
		<!-- Image -->
		<section class="relative mx-auto w-full">
			<div class="relative top-10 right-0 left-0 mx-auto w-[95%] md:top-24">
				<img
					src="https://image.tmdb.org/t/p/original/5syRZHBCzzCwkluq7EMrE8vYdlE.jpg"
					alt="Julia Garner in Weapons (2025)."
					width={1920}
					height={1080}
					decoding="async"
					loading="eager"
					class="animate-fade-in aspect-[143/100] rounded-3xl rounded-br-none rounded-bl-none object-cover"
				/>
				<div class="easing-gradient absolute top-0 right-0 left-0 size-full"></div>
				<span
					class="text-foreground/70 absolute top-1/2 -right-8 z-10 -rotate-90 text-[0.625rem] font-medium tracking-wide text-nowrap md:text-sm md:tracking-normal"
				>
					Weapons (2025)
				</span>
			</div>

			<!-- Hero Text -->
			<section
				class="absolute top-11/12 right-0 left-0 z-50 mx-auto mb-5 w-fit text-center md:top-4/5 md:mb-10"
			>
				<div class="mb-4 md:mb-6">
					<h2 class="text-[1.375rem] font-bold md:text-4xl md:tracking-tight">
						From premieres to finales.
					</h2>
					<p class="mt-1 text-sm font-semibold md:mt-2 md:text-[1.125rem] md:tracking-wide">
						Every movie. Every show. Every moment.
					</p>
				</div>

				<!-- CTA -->
				<a href="/signup" class="inline-block">
					<div
						class="rounded-full border border-indigo-600 bg-indigo-800 px-14 py-2 shadow-md inset-shadow-xs inset-shadow-indigo-400 transition-colors duration-150 ease-in-out hover:bg-indigo-700"
					>
						<span class="text-foreground font-semibold tracking-wide"> Start Tracking </span>
					</div>
				</a>
			</section>
		</section>
	</main>
</div>

// web/apps/web/src/routes/index.tsx
import { createFileRoute, Link } from "@tanstack/react-router";

import theaterImg from "@/assets/images/theater.png";
import { Fingerprint, Ticket } from "lucide-react";

export const Route = createFileRoute("/")({
  component: LandingPage,
});

function LandingPage() {
  return (
    <div className="relative h-full">
      <header>
        <nav className="flex items-center justify-between pt-8">
          <Link to="/">
            <h1 className="text-3xl font-extrabold">FrameRate</h1>
          </Link>

          <div className="flex items-center gap-10 font-semibold">
            <Link to="/login" className="group/login flex items-center gap-2">
              <span className="text-gray transition-colors duration-200 group-hover/login:text-white">
                <Fingerprint size={18} />
              </span>
              Login
            </Link>

            <Link
              to="/signup"
              className="pill-bg group/signup peer flex items-center gap-2 rounded-full border border-transparent px-3.5 py-0.5"
            >
              <span className="text-gray transition-colors duration-200 group-hover/signup:text-white">
                <Ticket size={18} />
              </span>
              Create free account
            </Link>
          </div>
        </nav>
      </header>

      <main className="mx-auto px-20">
        {/* Images */}
        <section className="absolute top-0 right-0 left-0 -z-10 mx-auto w-full items-center">
          <img
            src={theaterImg}
            alt="A dark movie theater."
            width={1920}
            height={1080}
            decoding="async"
            loading="eager"
            className="animate-fade-in relative"
          />

          <div className="absolute top-24 right-0 left-0 mx-auto w-[90%]">
            <img
              src="https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg"
              alt="Joel and Ellie from the TV series The Last of Us, released in 2023."
              width={1920}
              height={1080}
              decoding="async"
              loading="eager"
              className="animate-fade-in"
            />
            <div className="backdrop-fade absolute top-0 right-0 left-0 z-10 size-full"></div>
            <div className="easing-gradient absolute top-0 right-0 left-0 size-full"></div>
            <span className="text-gray/40 absolute top-1/2 -right-4 z-10 -rotate-90 text-sm font-medium text-nowrap">
              The Last of Us (2023)
            </span>
          </div>
          <div className="side-bottom-fade absolute top-0 right-0 left-0 z-10 size-full"></div>
        </section>

        {/* Hero Text */}
        <section className="mb-10 pt-[475px] text-center">
          <div className="mb-8">
            <h2 className="text-[32px] font-bold tracking-tight">
              Movie madness, managed.
            </h2>
            <p className="mt-3 text-[18px] font-medium tracking-wide">
              Track your cinematic journey.
            </p>
          </div>

          {/* CTA */}
          <Link
            to="/signup"
            className="hover:bg-foreground relative rounded-full border border-white/70 px-12 py-1.5 font-bold tracking-wide text-white shadow-sm transition-all duration-200 ease-in hover:text-neutral-800"
          >
            Get started
          </Link>
        </section>
      </main>
    </div>
  );
}
