// web/src/lib/components/home/home-carousel.svelte
<script lang="ts">
	// import type { Trending } from '@/types/trending';

	import { slugify } from '$utils/strings';

	import { resolve } from '$app/paths';

	import Poster from '$components/shared/poster.svelte';
	import * as Carousel from '$components/ui/carousel/index.js';

	type Props = {
		trendingMovies: Trending<'movie'>[];
		trendingTv: Trending<'tv'>[];
	};

	let { trendingMovies, trendingTv }: Props = $props();

	let movieData = $state(trendingMovies);
	let tvData = $state(trendingTv);

	const groupedData = [
		{
			type: 'movie',
			title: 'Movies Making Waves',
			link: '/films/$id/$title',
			data: movieData
		},
		{
			type: 'tv',
			title: 'Series Sensations',
			link: '/series/$id/$title',
			data: tvData
		}
	];
</script>

<div class="animate-fade-in">
	{#each groupedData as group (group.title)}
		{@const { data } = group}

		<section class="carousel-container group/trending">
			<h2 class="mb-3 ml-2 text-lg font-medium">{group.title}</h2>
			<Carousel.Root
				opts={{
					align: 'start',
					startIndex: 0,
					skipSnaps: true
				}}
			>
				<Carousel.Content>
					{#each data as media, index (index)}
						{@const titleSlug = slugify(media.title)}
						{@const loadingStrategy = index < 7 ? 'eager' : 'lazy'}
						{@const fetchStrategy = index < 7 ? 'high' : 'low'}

						<Carousel.Item>
							<a href={resolve(group.link, { id: String(media.id), title: titleSlug })}>
								<Poster
									title={media.title}
									src={media.posterPath}
									fetchSize="w342"
									width={160}
									height={240}
									perspectiveEnabled={false}
									scale={105}
									loading={loadingStrategy}
									fetchPriority={fetchStrategy}
									classes="w-fit aspect-[2/3] h-[160px] md:h-[195px] lg:h-[245px]"
								/>
							</a>
						</Carousel.Item>
					{/each}
				</Carousel.Content>
				<Carousel.Previous
					class="group/trending hidden animate-fade-in md:group-hover/trending:flex"
				/>
				<Carousel.Next class="group/trending hidden animate-fade-in md:group-hover/trending:flex" />
			</Carousel.Root>
		</section>
	{/each}
</div>

// web/src/features/home/components/HomeCarousel.tsx
"use client";

import type { Trending } from "@/types/tmdb.types";

import { useEffect, useState } from "react";
import Link from "next/link";

import useFetchTrending from "@/hooks/useFetchTrending";

import Poster from "@/components/Poster";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { getSimpleTitle } from "@/lib/utils";

export default function HomeCarousel() {
  const [movieData, setMovieData] = useState<Trending<"movie">[]>();
  const [tvData, setTvData] = useState<Trending<"tv">[]>();

  const movieTrendingData = useFetchTrending("movie", "week");
  const tvTrendingData = useFetchTrending("tv", "week");

  useEffect(() => {
    if (movieTrendingData && movieTrendingData.length > 18) {
      setMovieData(movieTrendingData.slice(0, 18));
    }

    if (tvTrendingData && tvTrendingData.length > 18) {
      setTvData(tvTrendingData.slice(0, 18));
    }
  }, [movieTrendingData, tvTrendingData]);

  return (
    <div className="animate-fade-in-fast">
      <section className="carousel-container group/trending">
        <h2 className="mb-2 ml-2 text-lg font-medium">Movies Making Waves</h2>
        <Carousel
          opts={{
            align: "start",
            startIndex: 0,
            skipSnaps: true,
          }}
        >
          <CarouselContent>
            {movieData?.map((movie) => {
              const simpleTitle = getSimpleTitle(movie.title);

              return (
                <CarouselItem
                  key={movie.id}
                  className="md:basis-1/5 xl:basis-1/6"
                >
                  <Link href={`/film/${movie.id}/${simpleTitle}`}>
                    <div className="transition-all duration-150 hover:scale-105">
                      <Poster
                        title={movie.title}
                        src={movie.posterPath}
                        fetchSize="w342"
                        width={160}
                        height={240}
                        perspectiveEnabled={false}
                        classes="animate-fade-in carousel-item w-[170px] h-[255px]"
                      />
                    </div>
                  </Link>
                </CarouselItem>
              );
            })}
          </CarouselContent>
          <CarouselPrevious className="group/trending hidden animate-fade-in-fast md:group-hover/trending:flex" />
          <CarouselNext className="group/trending hidden animate-fade-in-fast md:group-hover/trending:flex" />
        </Carousel>
      </section>

      <section className="carousel-container group/trending">
        <h2 className="mb-3 ml-2 text-lg font-medium">Series Sensations</h2>
        <Carousel
          opts={{
            align: "start",
            startIndex: 0,
            skipSnaps: true,
          }}
        >
          <CarouselContent>
            {tvData?.map((series) => {
              const simpleTitle = getSimpleTitle(series.title);

              return (
                <CarouselItem
                  key={series.id}
                  className="md:basis-1/5 xl:basis-1/6"
                >
                  <Link href={`/series/${series.id}/${simpleTitle}`}>
                    <div className="transition-all duration-150 hover:scale-105">
                      <Poster
                        title={series.title}
                        src={series.posterPath}
                        fetchSize="w342"
                        width={160}
                        height={240}
                        perspectiveEnabled={false}
                        classes="carousel-item w-[170px] h-[255px]"
                      />
                    </div>
                  </Link>
                </CarouselItem>
              );
            })}
          </CarouselContent>
          <CarouselPrevious className="group/trending hidden animate-fade-in-fast md:group-hover/trending:flex" />
          <CarouselNext className="group/trending hidden animate-fade-in-fast md:group-hover/trending:flex" />
        </Carousel>
      </section>
    </div>
  );
}
