// web/src/routes/(auth)/signup/+page.svelte
<script lang="ts">
	import { CircleArrowLeft, X } from '@lucide/svelte';

	import { resolve } from '$app/paths';

	import AuthContent from '$components/auth/AuthContent.svelte';
	import AuthFooter from '$components/auth/AuthFooter.svelte';
	import RotatingQuotes from '$components/auth/RotatingQuotes.svelte';
	import SignupForm from '$components/auth/SignupForm.svelte';

	let pageState = $state({ page: 1 });
	let reduceMotion = $state(false);

	$effect(() => {
		const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
		reduceMotion = mq.matches;
		const handler = (e: MediaQueryListEvent) => (reduceMotion = e.matches);
		mq.addEventListener?.('change', handler);

		return () => mq.removeEventListener?.('change', handler);
	});

	function handleClick() {
		pageState.page = 1;
	}
</script>

{#if !reduceMotion}
	<div
		aria-hidden={true}
		class="signup-animated-mesh absolute top-24 right-0 bottom-0 left-0 m-auto h-1/2 w-1/2"
	></div>
{/if}

<div
	aria-hidden={true}
	class="pointer-events-none fixed inset-0 z-0 bg-black/70 backdrop-blur-3xl"
></div>

<main class="relative flex w-full flex-1 flex-col items-center justify-center">
	<a
		href={resolve('/')}
		aria-label="Close and go to home"
		class="absolute top-2 left-2 rounded-full bg-white/[0.03] p-1 text-foreground transition-colors duration-200 hover:bg-white/5 md:top-8"
	>
		<X size={18} />
	</a>

	<div class={`mb-3 h-12 ${pageState.page === 2 ? 'block' : 'hidden'}`}>
		<RotatingQuotes />
	</div>

	<div class="relative animate-fade-in">
		{#if pageState.page === 1}
			<AuthContent
				title="Welcome to FrameRate"
				description="Thank you for being an early adopter. Let's set up your account."
			/>
		{/if}

		<section>
			{#if pageState.page === 2}
				<button
					type="button"
					onclick={handleClick}
					class="mb-7 w-fit text-gray transition-colors duration-200 hover:text-foreground"
				>
					<CircleArrowLeft size={32} strokeWidth={1.1} />
				</button>
			{/if}
			<SignupForm {pageState} />
		</section>
	</div>
</main>

<AuthFooter text="Already have an account?" linkText="Login" linkTo="/login" />

// web/src/app/(auth)/signup/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";

import { CircleArrowLeft, X } from "lucide-react";

import AuthContent from "@/features/auth/components/AuthContent";
import AuthFooter from "@/features/auth/components/AuthFooter";
import RotatingQuotes from "@/features/auth/components/RotatingQuotes";
import SignupForm from "@/features/auth/components/SignupForm";

import "../gradients.css";

export default function SignupPage() {
  const [page, setPage] = useState(1);

  function handleClick() {
    setPage(1);
  }

  return (
    <>
      <div
        aria-hidden={true}
        className="signup-animated-mesh absolute bottom-0 left-0 right-0 top-0 m-auto h-[400px] w-[500px]"
      />
      <div
        aria-hidden={true}
        className="absolute left-0 top-0 z-0 size-full bg-black/75 backdrop-blur-3xl"
      />
      <main className="relative mt-8 flex h-full flex-col items-center justify-center">
        <Link
          href="/"
          className="absolute left-2 top-0 rounded-full bg-white/[0.03] p-1 text-white transition-colors duration-200 hover:bg-white/5"
        >
          <X size={18} />
        </Link>

        <div className={`mb-24 h-12 ${page === 2 ? "block" : "hidden"}`}>
          <RotatingQuotes />
        </div>

        <div className="relative bottom-[70px]">
          {page === 1 && (
            <AuthContent
              title="Welcome to FrameRate"
              description="Thank you for being an early adopter. Let's set up your account."
            />
          )}

          <section>
            {page === 2 && (
              <button
                type="button"
                onClick={handleClick}
                className="mb-2 w-fit text-gray transition-colors duration-200 hover:text-white"
              >
                <CircleArrowLeft size={32} strokeWidth={1.1} />
              </button>
            )}
            <SignupForm page={page} setPage={setPage} />
          </section>
        </div>
      </main>

      <AuthFooter
        text="Already have an account?"
        linkText="Login"
        linkTo="/login"
      />
    </>
  );
}
