// web/src/lib/components/shared/header.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { page } from '$app/state';

	import { userStore } from '$stores/user-store.svelte';

	let { title }: { title?: string } = $props();
</script>

<header class="flex h-24 items-center justify-between md:h-[115px]">
	<div class="flex flex-col justify-center gap-3 md:flex-row md:items-center">
		<a href={resolve('/home')} class="mr-2 flex flex-col text-2xl leading-5">
			<span>FrameRate</span>
		</a>
		<div>
			<h1 class="text-lg font-semibold md:text-xl">
				{page.url.pathname === '/home' ? `Hello, ${userStore.name}` : title}
			</h1>
		</div>
	</div>
</header>

// web/src/components/header.tsx
import type { ReactNode } from 'react';

import { useEffect } from 'react';

import { useQuery } from '@tanstack/react-query';
import { Link, useLocation } from '@tanstack/react-router';
import { toast } from 'sonner';

import { authClient } from '@/lib/auth-client';
import { useAuthStore } from '@/store/auth/auth-store';

type HeaderProps = {
  title?: string;
  children?: ReactNode;
};

export default function Header({ title, children }: HeaderProps) {
  const { data: queryData, isError } = useQuery({
    queryKey: ['session'],
    queryFn: () => authClient.getSession(),
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
  });

  const { name, setEmail, setName, setUsername } = useAuthStore();
  const pathname = useLocation({
    select: (location) => location.pathname,
  });

  useEffect(() => {
    if (isError) {
      setName('User');
      toast.error('Something went wrong while getting user information!', {
        duration: 5000,
      });
      return;
    }

    const user = queryData?.data?.user;

    if (user) {
      setEmail(user.email);
      setName(user.name);
      setUsername(user.username!);
    }
  }, [queryData, setEmail, setName, setUsername, isError]);

  return (
    <header className="flex h-24 items-center justify-between md:h-[115px]">
      <div className="flex flex-col justify-center gap-3 md:flex-row md:items-center">
        <Link to="/home" className="mr-2 flex flex-col text-2xl leading-5">
          <span>FrameRate</span>
        </Link>
        <div>
          <h1 className="text-lg font-semibold md:text-xl">
            {pathname === '/home' ? `Hello, ${name}` : title}
          </h1>
        </div>
      </div>

      <div>{children}</div>
    </header>
  );
}
